# Generated by Django 6.0.5 on 2026-06-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='tipo_usuario',
            new_name='tipo',
        ),
    ]
