# Generated by Django 6.0.5 on 2026-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turnopasante',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turnopasante',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Turno Mañana'), ('TARDE', 'Turno Tarde')], default='MAÑANA', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='turnopasante',
            unique_together={('pasante', 'dia', 'turno')},
        ),
    ]
