# Generated by Django 6.0.5 on 2026-05-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_turnopasante_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasante',
            name='nota_final',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota Final'),
        ),
    ]
