# Generated by Django 6.0.5 on 2026-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_pasante_nota_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasante',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
