# Generated by Django 6.0.5 on 2026-06-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_pasante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(default='APROBADO', max_length=20),
        ),
    ]
