# Generated by Django 6.0.5 on 2026-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_registroasistencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
