# Generated by Django 6.0.5 on 2026-06-15 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_areaempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasante',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='pasante',
            name='supervisores',
            field=models.ManyToManyField(blank=True, related_name='pasantes_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
    ]
