# Generated by Django 6.0.5 on 2026-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_remove_pasante_supervisor_pasante_supervisores'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaempresa',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nombre del responsable oficial según RRHH', max_length=255, null=True),
        ),
    ]
